### PR TITLE
Use `bin` target name instead of package name as default

### LINKED ISSUE #156: `cargo-bundle` should use `bin` target name instead of package name
My application's binary name is different from its package name.

```toml
[package]
name = "foo-app"

[[bin]]
name = "foo"
path = "src/main.rs"
```

This is necessary to avoid package name conflict on crates.io. However, cargo-bundle uses the `package.name` to find a binary name. Due to the above configuration, `target/release/foo` exists but `target/release/foo-app` does not exist in my project. As the result, `cargo bundle` reported the following error message:

```
error: Failed to copy binary from "/path/to/my-app/target/release/foo-app"
  Caused by: "/path/to/my-app/target/release/foo-app" does not exist
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
   1: backtrace::backtrace::trace
   2: backtrace::capture::Backtrace::create
   3: backtrace::capture::Backtrace::new_unresolved
   4: error_chain::backtrace::imp::InternalBacktrace::new
   5: <error_chain::State as core::default::Default>::default
   6: cargo_bundle::Error::from_kind
   7: <cargo_bundle::Error as core::convert::From<alloc::string::String>>::from
   8: <T as core::convert::Into<U>>::into
   9: cargo_bundle::bundle::common::copy_file
  10: cargo_bundle::bundle::osx_bundle::copy_binary_to_bundle
  11: cargo_bundle::bundle::osx_bundle::bundle_project
  12: cargo_bundle::bundle::bundle_project
  13: core::ops::function::FnOnce::call_once
  14: core::result::Result<T,E>::and_then
  15: cargo_bundle::run
  16: cargo_bundle::main
  17: core::ops::function::FnOnce::call_once
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal
  21: std::rt::lang_start
  22: main
```

Expected behavior is that cargo-bundle uses the `bin` target name (`foo`) instead of the package name (`foo-app`) to find the binary file in `target` directory.

### PR DESCRIPTION
**Pull request by rhysd**
Fixes #156

### CODE REVIEW

File: src/bundle/settings.rs [hunk 1]
```diff
@@ -157,8 +157,17 @@ impl Settings {
             bail!("No [package.metadata.bundle] section in Cargo.toml");
         };
         let (bundle_settings, mut binary_name) = match build_artifact {
-            // TODO: this is wrong. Package can have multiple binaries and none of them has to be named the same way as package itself
-            BuildArtifact::Main => (bundle_settings, package.name.clone()),
+            BuildArtifact::Main => {
+                if let Some(target) = package
+                    .targets
+                    .iter()
+                    .find(|target| target.kind.iter().any(|k| k == "bin"))
```
Comment (mdsteele) [inline src/bundle/settings.rs:164]: Can this just be `target.kind.contains("bin")`?

File: Readme.md [hunk 2]
```diff
@@ -37,8 +37,8 @@ There are several fields in the `[package.metadata.bundle]` section.
 
 These settings apply to bundles for all (or most) OSes.
 
- * `name`: The name of the built application. If this is not present, then it will use the `name` value from
-           your `Cargo.toml` file.
+ * `name`: The name of the built application. If this is not present, then it will use the `name` value from `bin`
+           target in your `Cargo.toml` file.
```
Comment (mdsteele) [inline Readme.md:41]: Which `bin` does it choose if there is more than one?

File: src/bundle/settings.rs (hunk 1 above)
Comment (rhysd) [reply src/bundle/settings.rs:164]: It causes a compile error because `target.kind` is `Vec<String>`. `target.kind.contains(&"bin".to_string())` works, but it causes redundant heap allocation.

File: Readme.md (hunk 2 above)
Comment (rhysd) [reply Readme.md:41]: First one is chosen. It is my understanding that multiple `bin` targets are not supported.
