### PR TITLE
replace certain characters in plist entry

### LINKED ISSUE #191: bundle fails to launch on macOS Sequoia
I am able to launch bundles that have been bundled on previous macOS versions, but my .app that was bundled on macOS sequoia using `cargo bundle` fails to launch reporting that it is either damaged or incomplete. The binary itself runs fine.

### PR DESCRIPTION
**Pull request by hacknus**
should fix #191 .

### CODE REVIEW

File: src/bundle/osx_bundle.rs [hunk 1]
```diff
@@ -74,6 +75,24 @@ fn copy_binary_to_bundle(bundle_directory: &Path, settings: &Settings) -> crate:
...
+impl<T: AsRef<str>> PlistEntryFormatter for T {
+    fn format_plist_entry(&self) -> String {
+        let input = self.as_ref();
+        let escaped: Cow<str> = if input.contains("&") {
+            Cow::Owned(input.replace("&", "&amp;")) // Modify only if needed
+                                                    //
+                                                    // add other necessary modifications here...
+                                                    //
+        } else {
+            Cow::Borrowed(input) // No allocation if no `&` is present
```
Comment (mdsteele) [inline src/bundle/osx_bundle.rs:91]: We're not really avoiding an allocation, since below we still make a copy when we `escaped.to_string()`, right?  Seems like we could skip the `Cow` and just:

```
if input.contains("&") {
    return input.replace("&", "&amp;");
} else {
    return input.to_string();
}
```

In fact, since the string gets copied either way, we could just skip the conditional block entirely and just `return input.replace("&", "&amp;");`

Comment (hacknus) [reply src/bundle/osx_bundle.rs:91]: Yes! Thanks!
